### ISSUE TITLE
days.json

### ISSUE THREAD

**Issue by r3m0dul8** [SilvrrGIT/HomeAssistant#124] opened 2019-01-04 16:25 UTC
Hey, I've switched my Hassio install and just love your config but can't seem to get my own days.json to work but it works when directly pointed to yours, I'm a newbie to all this so be gentle - any advice as the morning reports just come out Day is Unknown. I'm in the UK and have modified your JSON file, hopefully I've done it correctly but please if you could direct me to what I have done wrong? Thanks

https://github.com/r3m0dul8/hassio/tree/master/json_data

**Comment by SilvrrGIT** [comment] 2019-01-04 16:37
It looks like you are missing a comma after a few lines.  I submitted a pull request with the necessary changes.  

A JSON linter is helpful.  https://jsonlint.com/  Paste the JSON in there and it will point out errors.  Github also highlighted the errors.  You have to know a bit about JSON formatting to make sense of what these tools provide though.  

Hope that helps, let me know if it doesn't.

**Comment by SilvrrGIT** [comment] 2019-01-07 16:56
Closing this as it looks like the issue is fixed.

**Closed by SilvrrGIT** 2019-01-07 16:56 UTC
